# Generated by Django 3.1.3 on 2020-11-22 15:29

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('category_description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=30)),
                ('reporter_info', models.TextField()),
                ('file', models.ImageField(upload_to='uploads/', verbose_name='Image Reporter')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
                ('summary', models.CharField(max_length=100)),
                ('page_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('file', models.ImageField(upload_to='uploads/', verbose_name='Image article')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.category')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.reporter')),
            ],
        ),
    ]
